%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8]"
    EXTERNAL_NET: "!$HOME_NET"
af-packet:
  - interface: eth0
outputs:
  - fast:
      enabled: yes
  - eve-log:
      enabled: yes
      types: [alert, http, dns, tls, ssh]
