input {
  file {
    path => "/var/log/suricata/eve.json"
    codec => json
  }
}
filter {
  if [event_type] == "alert" {
    mutate { add_tag => ["security-alert"] }
  }
}
output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "security-lab-%{+YYYY.MM.dd}"
  }
}
